import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

let url = "www.thecocktaildb.com/api/json/v1/1/search.php?s=";

const Home: NextPage = ({ articles }: any) => {
  const [searchTerm, setSearchTerm] = useState("");
  console.log({ articles });
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </div>
  );
};

export default Home;
